# Actuator configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

# Error handling
server:
  error:
    include-message: always
    include-binding-errors: always

# Http logging configuration
logging:
  level:
    org:
      zalando:
        logbook: TRACE

logbook:
  exclude:
    - /actuator/health
  filter.enabled: true
  secure-filter.enabled: true
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
    write:
      chunk-size: 1000
